name := "chisel3-tutorial"
version := "1.0"
scalaVersion := "2.11.11"
libraryDependencies += "edu.berkeley.cs" %% "chisel3" % "3.1-SNAPSHOT" 
libraryDependencies += "edu.berkeley.cs" %% "chisel-iotesters" % "latest.release"
